### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by muesli** [mariusor/go-littr#30]
I noticed something a bit unusual in the `Go` world, which is the repo name having a `.go` suffix. This is known to cause various problems with tooling, `go get` and even `go build`. I know you're using a `Makefile` to work around that, but unless you plan a second app called `littr` I'd like to suggest renaming the repository to simply `littr`.

**Comment by mariusor** [comment]
OK, noted. 
Probably I need to come up with a better name anyway, because littr me is not suggestive in any way, and just littr seems incomplete to me. :)

**Comment by muesli** [comment]
I agree, we can probably come up with a slightly more attractive name, even though I kinda get the origin of "littr" :smile:

**Comment by mariusor** [comment]
Do you think it would be too presumptuous to call it "feddit" (or fedit) ? Or raise issues with reddit's trademark?

**Comment by muesli** [comment]
Good question! I think it's a bit risky indeed. Probably better to find a separate name that also gives the project a bit of an identity. Just my 2 cents.

**Comment by mariusor** [comment]
Yes, but this is the BIGGEST problem in computer science: naming things. I'm not good at it.

"Brutal links" ?

**Comment by mariusor** [comment]
Fedli ?

**Comment by mariusor** [comment]
I guess that until I decide upon another name I'll rename the project from littr.go -> go-littr.

I hope this is better.

**Comment by muesli** [comment]
At least that'll unbreak the standard Go tools, I'm all for it!
