### ISSUE TITLE
Validate HTML

### ISSUE THREAD

**Issue by skyfaller** [mariusor/go-littr#32]
Can we improve the results of running littr.me through an HTML validator? https://validator.w3.org/nu/?doc=https%3A%2F%2Flittr.me

The only error (as opposed to mere warnings) seems to be 24 copies of "Element a is missing required attribute href." Can we get an href into the code there? Is it necessary to have links that don't go anywhere?

I recognize that validators can be annoying and inflexible at times (and sometimes out of date / unaware of the latest standards), but validation can help catch mistakes in our code, and standards compliance is how we keep the web open to everyone, not just the currently dominant players, so I think it's worth the effort. I also understand this is alpha software, but I think that getting into the habit of validating HTML is a good idea.

**Comment by skyfaller** [comment]
In this specific instance, I suspect that instead of an "a" you might want to use a button: https://christianheilmann.com/2019/02/05/links-that-dont-go-anywhere-should-be-buttons/

**Comment by mariusor** [comment]
Thank you for the ticket. 

I think a plain `<span>` would be more appropriate, as the difference between the `<a/>`s with the href property and the ones without it, is just if the current logged user is allowed to vote or not on the item. There's no Javascript handling of non-href ones.

If you have the time, please feel free to open a PR for it.

**Comment by mariusor** [comment]
So, in the end I added `href="#"` to disabled links and did some css/js stuff to mark them as "inactive".

You can check it on https://brutalinks.tech (which is like a qa more up to date version of littr.me)
