### ISSUE TITLE
Registration/login appears broken

### ISSUE THREAD

**Issue by StarFscker** [mariusor/go-littr#33]
Made a couple accounts to test, this is current behavior on littr.me

Account creation goes well, but once you try logging in, if you type the password correctly it goes through the motions and redirects you to the front page. No obvious sign that you are logged in, and if you click "Log In" again, it will bring you to the normal log in page. 

If you type the password incorrectly in login, it will redirect to the login page but not give any sign that you had the wrong password.

**Comment by mariusor** [comment]
Thank you, I'll take a look. What browser are you using?

**Comment by StarFscker** [comment]
Hello, I've tested it in Brave and Firefox. In Firefox, there were no extensions installed. The behavior is the same in both.

**Comment by mariusor** [comment]
On OSX by any chance?

**Comment by StarFscker** [comment]
Hello, no this is on a Debian-based system with KDE as the desktop.

**Comment by mariusor** [comment]
OK, fixed.
