### ISSUE TITLE
"Discussion" labels confusing for self-posts

### ISSUE THREAD

**Issue by jprjr** [mariusor/go-littr#47]
Hi there!

I was checking out https://brutalinks.tech and just thought I'd report what I think is a UX issue.

Using this post as an example: https://brutalinks.tech/~HT472/a2473c7b-797e-49d8-b913-630c79d86258

When viewed on the front page, there's two links, both labeled "Discussion", but they lead to two different places.

The first appears after the post title and (I believe) leads to a page with other self-posts.

The second appears on the line with the date posted, username, etc, and leads to the individual discussion.

**Comment by mariusor** [comment]
Thank you for your interest, I agree it's confusing. 

I think I iterated through various labels for these and this is the latest option.

Would it be less confusing if "(discussion)" would be "(discussions)" and the one leading to the actual comments would be "comments" ?
